### ISSUE TITLE
send-zabbix-data: Could not find attribute report

### ISSUE THREAD

**Issue by Hellaenergy** [a13m/openshift-zabbix-agent-cartridge#1]
I'm getting the following error when running:

$OPENSHIFT_ZABBIX_AGENT_DIR/usr/bin/send-zabbix-data
Could not find attribute report
/var/lib/openshift/5363cfc66277979e71000037/zabbix-agent//usr/bin/send-zabbix-data:114:in `<main>': undefined method`each' for nil:NilClass (NoMethodError)

This is on OpenShift Enterprise 2.0

**Comment by a13m** [comment]
The problem here is that oo-cgroup-read did not have a "report" option until very recently.  It was addressed here:  https://bugzilla.redhat.com/show_bug.cgi?id=1056713

Without that functionality, it's necessary to make individual calls for each cgroup attribute you'd like to read.  An old revision of send-zabbix-data did this:

https://github.com/a13m/openshift-zabbix-agent-cartridge/blob/4d496590519adedc947c20341cd07e707950fede/usr/bin/send-zabbix-data.rb

The performance of this approach is not good, though (at least not for our small gears in OpenShift Online).  I will try to add code to deal with backward compatibility.

**Comment by Hellaenergy** [comment]
Upgrading to OSE 2.1 resolved this issue.
